### ISSUE TITLE
Having a "enabledIn" option additionally with "disabledIn"

### ISSUE THREAD

**Issue by S-Stanley** [MASSHUU12/too-long-line-limit#3]
It has been a few days since I'm using your extension, I was wondering if there would be a possibility to select the languages I want to activate instead of deactivating (I'm using it only for markdown and SQL).

Maybe a good solution could be to have a `enabledIn` parameter, additionally to`disabledIn`, the former overriding the later if set.

If you agree, I would like to know if I can work on this and contribute to your project

**Comment by MASSHUU12** [comment]
Great idea, if you want to work on it, of course you can. I'd be happy to welcome any improvements or new features.
